export const GETHIGHESTNUMBERS = 'GETHIGHESTNUMBERS';
export const LOADMYSEARCHES = 'LOADMYSEARCHES';
export const SEARCHAPLAYER = 'SEARCHAPLAYER';
export const GETERROR = 'GETERROR';
export const CLEARERROR = 'CLEARERROR';
export const CLEARPLAYER = 'CLEARPLAYER';
export const SEARCHING = 'SEARCHING';
